config/routes.rb
Rails.application.routes.draw do
  root "clinicians#index"
  resources :clinicians

end

app/models/clinician.rb
class Clinician < ActiveRecord::Base
 geocoded_by :address
 after_validation :geocode, :if => :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clinicians_controller.rb
class CliniciansController < ApplicationController
  before_action :set_clinician, only: [:show, :edit, :update, :destroy]


  def index
    if params[:search].present?
      @clinicians = Clinician.near(params[:search], 5) 

    else
      @clinicians = Clinician.all
    end

    @hash = Gmaps4rails.build_markers(@clinicians) do |clinician, marker|
      marker.lat clinician.latitude
      marker.lng clinician.longitude
    end


  end

  def show
  end

  def new
    @clinician = Clinician.new
  end

  def edit
  end


  def create
    @clinician = Clinician.new(clinician_params)

    respond_to do |format|
      if @clinician.save
        format.html { redirect_to @clinician, notice: 'Clinician was successfully created.' }
        format.json { render :show, status: :created, location: @clinician }
      else
        format.html { render :new }
        format.json { render json: @clinician.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @clinician.update(clinician_params)
        format.html { redirect_to @clinician, notice: 'Clinician was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinician }
      else
        format.html { render :edit }
        format.json { render json: @clinician.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @clinician.destroy
    respond_to do |format|
      format.html { redirect_to clinicians_url, notice: 'Clinician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_clinician
      @clinician = Clinician.find(params[:id])
    end

    def clinician_params
      params.require(:clinician).permit(:address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinicians_helper.rb
module CliniciansHelper
end

app/views/clinicians/_form.html.erb
<%= form_for(@clinician) do |f| %>
  <% if @clinician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinician.errors.count, "error") %> prohibited this clinician from being saved:</h2>

      <ul>
      <% @clinician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clinicians/edit.html.erb
<h1>Editing Clinician</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinician %> |
<%= link_to 'Back', clinicians_path %>

app/views/clinicians/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag clinicians_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clinicians.each do |clinician| %>
      <tr>
        <td><%= clinician.address %></td>
        <td><%= clinician.latitude %></td>
        <td><%= clinician.longitude %></td>
        <td><%= link_to 'Show', clinician %></td>
        <td><%= link_to 'Edit', edit_clinician_path(clinician) %></td>
        <td><%= link_to 'Destroy', clinician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clinician', new_clinician_path %>

<br>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<br>


<script type="text/javascript">

    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.map.centerOn(markers[0]); 
        handler.fitMapToBounds();
        handler.getMap().setZoom(12);
        
    });
</script>

app/views/clinicians/new.html.erb
<h1>New Clinician</h1>

<%= render 'form' %>

<%= link_to 'Back', clinicians_path %>

app/views/clinicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @clinician.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @clinician.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @clinician.longitude %>
</p>


<h3> Addresses </h3>
<ul>
<% for clinician in @clinician.nearbys(10) %>
	<li> <%= link_to clinician.address, clinician %> </li> (<%= clinician.distance.round(2) %> miles) </li>
<% end %>

</ul>



<%= link_to 'Edit', edit_clinician_path(@clinician) %> |
<%= link_to 'Back', clinicians_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nearmaps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>